volumes:
  db_data:
  
services:
  mysql:
    image: mysql:8.0
    container_name: etodo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3003:3306"
    volumes:
      - ./e-todo.sql:/docker-entrypoint-initdb.d/e-todo.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: etodo-backend
    restart: always
    ports:
      - "${PORT}:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql
    
  frontend:
    build: ./front-end
    container_name: frontend
    restart: always
    ports:
      - "3001:3001" 
    depends_on:
      - backend
    
# Chaque docker doit être parametré dans un docker-compose.yml
# Chaque docker doit avoir un dockerfile (sauf la database)